#!/usr/bin/env zsh

sudo apt-get install -y vim figlet tmux
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

pushd "$DOTFILES"
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "================== LINKING $folder =================="
    stow -Dt ~ "$folder"
    stow -St ~ "$folder"
done
popd
